server:
  port: 8082
  
spring:
  application:
    name: BRANCH-SERVICE  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone: http://localhost:8761/eureka/
  instance:
    hostname: localhost